name: coursier test
on: [workflow_dispatch]
jobs:
  run-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: laughedelic/coursier-setup@v1
        with:
          apps: 'ammonite'
      - run: sbt test
      - run: amm main.sc